import fs from 'node:fs';
import assert from 'node:assert/strict';
const source=fs.readFileSync('web/gateway-transport.js','utf8');
const {GatewayTransport}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
let absent=false,usb=true;const calls=[];
globalThis.fetch=async(url,options)=>{
 const [a,uid,c]=options.body.split('|');calls.push(c);
 if(c==='status'&&absent)return {ok:false,text:async()=>'DATA timeout'};
 if(c==='wake'&&usb)return {ok:false,text:async()=>'USB console connected; disconnect it before phone control'};
 return {ok:true,text:async()=>c==='gatewayinfo'?`META,${a},ABC${a},5.2,1.5,2`:c==='status'?`STATUS,${a},0,0,19.5,0,0,1,0,0,0,0,0`:'ACK'};
};
const g=new GatewayTransport({address:1,token:'mock'});
await g.api('ports');await g.api('logs?port=DATA1');
absent=true;await assert.rejects(g.api('logs?port=DATA1'));
assert.equal((await g.api('ports')).ports.find(p=>p.port==='DATA1').active,false);
absent=false;await g.api('connect',{port:'DATA1'});
assert.equal((await g.api('ports')).ports.find(p=>p.port==='DATA1').active,true);
await assert.rejects(g.motion('DATA1','position',1),/电脑串口/);
assert(!calls.some(c=>c.startsWith('posout')),'USB denial must not send target');
usb=false;await g.motion('DATA1','position',1);
await Promise.all([g.api('send',{port:'DATA1',command:'stop'}),g.api('send',{port:'DATA184',command:'stop'})]);
assert.equal(calls.filter(c=>c==='stop').length,2);
console.log('PASS drop/reconnect, translated USB refusal, no target on refusal, paired STOP (mock only)');
const originalFetch=globalThis.fetch;
globalThis.fetch=async()=>({ok:true,text:async()=>'STATUS,1,broken'});
await assert.rejects(g.api('connect',{port:'DATA1'}),/状态数据无效/);
await assert.rejects(g.motion('DATA1','position',1),/遥测过期/);
globalThis.fetch=originalFetch;
await g.api('connect',{port:'DATA1'});
const same=g.devices.get('DATA1');await g.discover();
assert.equal(g.devices.get('DATA1'),same,'discovery preserves in-flight telemetry object');
calls.length=0;
const results=await Promise.allSettled([g.motion('DATA1','position',1),g.motion('DATA1','position',2),g.motion('DATA1','position',3)]);
assert.equal(results[2].status,'fulfilled');
assert.deepEqual(calls.filter(c=>c.startsWith('posout')),['posout 3.0000 4095 1000']);
console.log('PASS malformed reconnect rejected; discovery preserves state; only latest queued target sent (mock only)');
