const fs=require('node:fs'),assert=require('node:assert/strict');
const firmware=fs.readFileSync('firmware/src/main.cpp','utf8');
assert(firmware.includes('const float lowerPwm = -pwmLimit;'));
assert(firmware.includes('const float upperPwm = pwmLimit;'));
assert(!firmware.includes('const bool useModelEnvelope'));
assert(firmware.includes('interactionGuard.update('));
assert(firmware.includes('if (protection.fault)'));
assert(firmware.includes('motorProfileVoltageDutyLimit(cascadeBusVoltage)'));
assert(firmware.includes('cascadeEmfVelocityDps = motor_control::emfVelocityEstimate('));
assert(firmware.includes('currentTarget - cascadeMeasuredCurrentA'));
assert(firmware.includes('15.0f * 360.0f * motorProfileGearRatio'));
assert(firmware.includes('cascadePositionMaxAccelerationDps2 = 40000.0f;'));
assert(firmware.includes('? interaction::operatingCurrentLimit(current) : min(cascadeVelocityMaxCurrentA, current)'));
assert(firmware.includes('constrain(cascadeCurrentCommandA, -operatingLimit, operatingLimit)'));
console.log('PASS measured-current voltage authority in all modes; reference ceiling, measured guard and voltage rails retained');
