import assert from 'node:assert/strict';
import {UsbChainTransport} from '../web/usb-chain-transport.js';
const usb=(port,serial)=>({port,hwid:'USB SER='+serial,esp32:true,active:true,telemetry_ok:true});
const a=usb('COM4','68EE8F5381E4'),b=usb('COM23','68EE8F52A79C');
let fail=false,session='s1',calls=[];
const registry=[{serial:'68EE8F5381E4',uid:'E481538FEE68',address:184},{serial:'68EE8F52A79C',uid:'9CA7528FEE68',address:1}];
const raw=async(path,body,timeout,keepalive)=>{
 calls.push({path,body,timeout,keepalive});
 if(path==='chain/topology')return {devices:registry};
 if(path.startsWith('logs?'))return {session_id:session};
 if(fail)throw Error('lost');
 const id=body.address===1?'9CA7528FEE68':'E481538FEE68';
 if(body.command==='gatewayinfo')return {uid:id,gear:5.2,current_limit:1.5,model_ke:.011,protocol:3};
 if(body.command==='status')return {reply:`STATUS,${body.address},0,0,19.5,0,0,1,0,0,0,0,0`};
 return {ok:true,accepted:true,reply:'ACK,1,accepted'};
};
const t=new UsbChainTransport(raw);
let r=await t.ports({ports:[a]});assert.equal(r.ports.length,2);assert.equal(r.ports[1].port,'DATA-1');
await t.api('logs?port=DATA-1');
await t.api('send',{port:'DATA-1',command:'sync status'});
assert.equal(calls.at(-1).path,'chain/query');assert.equal(calls.at(-1).body.command,'sync status');
await t.api('send',{port:'DATA-1',command:'wake'});
assert.equal(calls.at(-1).path,'chain/control');assert.equal(calls.at(-1).body.mode,'wake');
await t.api('send',{port:'DATA-1',command:'sync force 184 18 0.35 0 1200 4095 30000 0'});
assert.equal(calls.at(-1).body.mode,'sync_force');assert.equal(calls.at(-1).body.peer,184);
assert.equal(calls.at(-1).body.limit,1200);
await t.api('send',{port:'DATA-1',command:'sync stop'});
assert.equal(calls.at(-1).body.mode,'sync_stop');
await t.keepaliveControl('DATA-1','stop');
assert.equal(calls.at(-1).path,'chain/control');assert.equal(calls.at(-1).keepalive,true);
const originalDevice=t.devices.get('DATA-1');t.lastScan=0;await t.ports({ports:[a]});
assert.equal(t.devices.get('DATA-1'),originalDevice,'META refresh must preserve in-flight telemetry state');
originalDevice.failed=true;t.lastScan=0;await t.ports({ports:[a]});
assert.equal(originalDevice.failed,true,'META alone must not clear status failure');
await t.api('logs?port=DATA-1');
await t.motion('DATA-1','position',360);assert.equal(calls.at(-1).body.value,1);
await t.motion('DATA-1','velocity',720);assert.equal(calls.at(-1).body.value,2);
await t.motion('DATA-1','current',500);assert.equal(calls.at(-1).body.value,.5);
await t.motion('DATA-1','pwm',128);assert.equal(calls.at(-1).body.value,128);
assert.equal((await t.api('send',{port:'DATA-1',command:'sleep'})).acknowledged,true);
r=await t.ports({ports:[a,b]});assert.equal(r.ports.length,2);assert.equal(t.devices.size,0);
const bMaintenance={...b,active:false,telemetry_ok:false,maintenance:true};
t.lastScan=0;
r=await t.ports({ports:[a,bMaintenance]});
assert.equal(r.ports.filter(p=>p.port==='DATA-1').length,1,'maintenance peer must remain visible through DATA');
await assert.rejects(t.motion('DATA-1','current',500));
r=await t.ports({ports:[b]});assert.equal(r.ports[1].port,'DATA-184');
await assert.rejects(t.motion('DATA-184','current',500)); // no fresh sample yet
await t.api('logs?port=DATA-184');
fail=true;await assert.rejects(t.api('logs?port=DATA-184'));
await assert.rejects(t.motion('DATA-184','current',500));
fail=false;session='s2';t.lastScan=0;await t.ports({ports:[b]});
assert.equal(t.devices.get('DATA-184').last,0);
assert.equal((await t.api('logs?port=DATA-184')).session_id,'s2:E481538FEE68');
registry[0].address=7;t.lastScan=0;await t.ports({ports:[b]});
assert(!t.devices.has('DATA-184'));assert(t.devices.has('DATA-7'));
await assert.rejects(t.motion('DATA-7','current',100),'new ID needs fresh status');
await t.api('logs?port=DATA-7');await t.motion('DATA-7','current',100);
assert.equal(calls.at(-1).body.address,7);
await t.ports({ports:[]});assert.equal(t.devices.size,0);
console.log('PASS two entry directions, dedup, units, STOP ACK, stale/session/route guards; mocked I/O only');
