const fs=require('node:fs'),assert=require('node:assert/strict');
const wifi=fs.readFileSync('firmware/src/wifi_gateway.cpp','utf8');
const main=fs.readFileSync('firmware/src/main.cpp','utf8');
const server=fs.readFileSync('web/server.py','utf8');
const html=wifi.split('R"HTML(')[1].split(')HTML"')[0];
new Function(html.split('<script>')[1].split('</script>')[0]);
assert(wifi.includes('xTaskCreatePinnedToCore(task,"motor_wifi",8192,nullptr,1,nullptr,0)'));
assert(wifi.includes('xQueueSend(requests,&req,0)'));
assert(wifi.includes('req.deadline=millis()+500'));
assert(wifi.includes('server.header("X-Motor-Token")!=token'));
assert(main.includes('USB console connected; disconnect it before phone control'));
assert(main.includes('Expired queued request'));
assert(main.includes('Identity/protocol/target rejected; no motion sent'));
assert(!html.includes('setInterval('),'no unattended command renewal');
assert(!wifi.includes('handleCommand('),'HTTP task must never operate motor directly');
assert(wifi.includes('"Motor-%012llX",uid&0xffffffffffffULL'),'SSID must use full device identity');
const ssid=uid=>'Motor-'+(BigInt('0x'+uid)&0xffffffffffffn).toString(16).toUpperCase().padStart(12,'0');
assert.notEqual(ssid('E481538FEE68'),ssid('9CA7528FEE68'),'same vendor bytes must not collide');
assert(ssid('E481538FEE68').length<=32);
assert(wifi.includes('WiFi.softAP(networkName,nullptr,apChannel,false,4)'),'explicit open AP');
assert(wifi.includes('WiFi.softAPConfig(IPAddress(192,168,4,1)'),'explicit DHCP network');
assert(server.includes('"led auto"'),'desktop must allow automatic LED mode');
assert(wifi.includes('dhcpStatus()!=ESP_NETIF_DHCP_STARTED'),'check actual DHCP service');
assert(wifi.includes('ARDUINO_EVENT_WIFI_AP_STAIPASSIGNED'),'count assigned IP events');
assert(!wifi.includes('WiFi.softAPdisconnect('),'health check must not kick healthy clients');
const channel=uid=>1+5*Number((BigInt('0x'+uid)>>24n)%3n);
assert.notEqual(channel('E481538FEE68'),channel('9CA7528FEE68'));
assert(wifi.includes('dns.start(53,"*",WiFi.softAPIP())'));
assert(wifi.includes('dns.processNextRequest()'));
assert(wifi.includes('server.sendHeader("Location","http://192.168.4.1/",true)'));
assert(html.includes("scan(false).finally(poll)"),'initial discovery must be query-only');
assert(html.includes("setTimeout(poll,250)"),'bounded sequential read-only refresh');
assert(html.includes('stopPending=true;scanCancel=true'),'stop must not be dropped while querying');
console.log('PASS WiFi source contracts and page JS syntax; not radio/HTTP/hardware acceptance');
